version: '3.7'
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '8082:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.3.9
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
         ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
            - ${PWD}
